#!/usr/bin/env bash
# Transffers a file from client to a server
# [Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY]

if [[ $# -lt 3 ]]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else 
	# scp filepath_to_copy ssh -i filepath username@address:destination
	scp -o 'StrictHostKeyChecking=no' -i "$4" "$1" "$3"@"$2":~/
fi
