#!/usr/bin/env bash
# Generates a MYSQL dump file and creates a compressed archive out of it

archive=$(date +%d-%m-%Y).tar.gz

sudo mysqldump -A -u root -p "$1" | sudo tee backup.sql

touch "$archive"

tar -cvzf "$archive" backup.sql
