#!/usr/bin/env bash
# Generates a MYSQL dump file and creates a compressed archive out of it

archive=$(date +%d-%m-%Y).tar.gz
mysqldump -u root -p"$1" -all-databases > backup.sql
tar -cvzf "$archive" backup.sql
