#!/usr/bin/env bash
# Configures a server to listen on a particular port [Port 80]

sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
#sed -i "s/8080/80/g" /etc/nginx/sites-enabled/default
sudo service nginx restart
