#!/usr/bin/env bash
# Displays time for 12 hours and 59 minutes

hour=0
minutes=1

while [ $hour -ne 13 ]
do
	echo "Hour: $hour"
	for ((minutes=1; minutes < 60; minutes++))
	do
		echo "$minutes"
	done
	#echo "Hour: $hour"
	hour=$((hour + 1))
done
